### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by Niemandausduisburg** [hentaiOS/platform_vendor_hentai#3]
I got this error message while building.
[100% 41/41] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b 
out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build
-globs.ninja -o out/soong/build.ninja Android.bp
error: device/nokia/msm8998-common/gpt-utils/Android.bp:17:1: "libgptutils.msm89
98" depends on undefined module "generated_kernel_headers"
08:29:06 soong bootstrap failed with: exit status 1

**Comment by raphielscape** [comment]
We already dropped Kernel Header Generator

**Comment by Niemandausduisburg** [comment]
What can I do to fix the issue?

**Comment by mathpfvr** [comment]
you fixed bro?

**Comment by Niemandausduisburg** [comment]
I had to add the cross-compiler in device.mk. The error seems to be fixed.

**Comment by PeterHindes** [comment]
Can you explain what you did a little more? I'm having this issue too.
