### ISSUE TITLE
Missing module "generated_kernel_headers"

### ISSUE THREAD

**Issue by ech0devv** [hentaiOS/platform_vendor_hentai#4]
Hey, I need help with the following error:
```
[100% 1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/soong/.bootstrap/bin/soong_build")" && BUILDER="$PWD/$(basename "out/soong/.bootstrap/bin/soong_build"
)" && cd / && env -i "$BUILDER"     --top "$TOP"     --out "out/soong"     -n "out"     -d "out/soong/build.ninja.d"     
-t -l out/.module_paths/Android.bp.list -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja --avail
able_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used Android.bp
error: hardware/oneplus/hidl/fingerprint/Android.bp:1:1: "libudfps_extension.oneplus" depends on undefined module "genera
ted_kernel_headers"
20:05:34 soong bootstrap failed with: exit status 1
```
Although there have been issues about this, neither specified the fix. I'm building for my OnePlus 9 as an experiment, with known good trees, however I believe that this is an issue with the vendor. Any help?

Here's the kernel I'm using:
https://github.com/chandu078/kernel_oneplus_sm8350

**Comment by ech0devv** [comment]
Also, here's my hardware tree:
https://github.com/PixelExperience/hardware_oneplus

**Comment by ech0devv** [comment]
How much would it break if I were to add some stuff from this file (alongside the directories that it depends on):
https://github.com/PixelExperience/vendor_aosp/blob/twelve/build/soong/Android.bp
Into the vendor/hentai/build/soong/Android.bp?

**Comment by VTVishwanath** [comment]
How did you fix the issue? @ech0devv
